<?php

/**
 * Implements hook_block_info().
 */
function hadis_category_block_info()
{
    $blocks = array();

    $blocks['hadis_category'] = array(
        'info' => t('Hadis Category'),
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hadis_category_block_view($delta = '')
{
    $block = array();

    switch ($delta) {
        case 'hadis_category':
            $block['content'] = hadis_category_view();
            break;
    }

    return $block;
}

function hadis_category_view()
{
    ob_start();
    include dirname(__FILE__) . '/front-panel-hadis-category.php';
    $output = ob_get_clean();

    // Block output in HTML with div wrapper
    $block = array(
        'body' => array(
            '#type'   => 'markup',
            '#markup' => $output,
        )
    );

    return $block;

}