### Public Pages ###

iHadis_public_pages:
    resource: "@IhadisWebBundle/Controller"
    prefix:   /ui2
    type: annotation

ihadis_homepage:
    pattern:  /
    defaults: { _controller: IhadisWebBundle:Default:index }

ihadis_status:
    pattern:  /_status
    defaults: { _controller: IhadisWebBundle:Default:status }

ihadis_search:
    pattern: /search/{keyword}/{page}
    defaults: { _controller: IhadisWebBundle:Default:search, page: 1 }

ihadis_public_report_hadith:
    pattern: /hadith/report
    defaults: { _controller: IhadisWebBundle:Default:report }
    methods: [POST]

about_us:
    pattern: /page/about-us
    defaults: { _controller: IhadisWebBundle:StaticPages:aboutUs }

disclaimer:
    pattern: /page/disclaimer
    defaults: { _controller: IhadisWebBundle:StaticPages:disclaimer }

join_team:
    pattern: /page/join-team
    defaults: { _controller: IhadisWebBundle:StaticPages:joinTeam }

feedback:
    pattern: /page/feedback
    defaults: { _controller: IhadisWebBundle:StaticPages:feedback }

under_construction:
    pattern: /page/under_construction
    defaults: { _controller: IhadisWebBundle:StaticPages:incomplete }

ihadis_pdf_book:
    pattern: /pdf/{bookName}
    defaults: { _controller: IhadisWebBundle:Default:pdfBook }

ihadis_public_test:
    pattern: /test
    defaults: { _controller: IhadisWebBundle:Default:test }

ihadis_public_book:
    pattern: /{slug}
    defaults: { _controller: IhadisWebBundle:Default:book }

ihadis_public_chapter:
    pattern: /{slug}/{number}
    defaults: { _controller: IhadisWebBundle:Default:chapter }

ihadis_public_goto:
    pattern: /goto/{slug}/{numberPrimary}
    defaults: { _controller: IhadisWebBundle:Default:goto }

ihadis_public_hadith:
    pattern: /{slug}/{number}/{numberPrimary}
    defaults: { _controller: IhadisWebBundle:Default:hadith }