### Public Pages ###

ihadis_homepage:
    pattern:  /
    defaults: { _controller: IhadisWebBundle:Default:index }

ihadis_public_report_hadith:
    pattern: /hadith/report
    defaults: { _controller: IhadisWebBundle:Default:report }
    methods: [POST]

ihadis_public_book:
    pattern: /{slug}
    defaults: { _controller: IhadisWebBundle:Default:book }

ihadis_public_chapter:
    pattern: /{slug}/{number}
    defaults: { _controller: IhadisWebBundle:Default:chapter }

ihadis_public_hadith:
    pattern: /{slug}/{number}/{numberPrimary}
    defaults: { _controller: IhadisWebBundle:Default:hadith }


