<?php

include_once __DIR__ . '/hadis_input_functions.php';

function hadis_input_menu()
{
    $items = array();

    $items['hadith/new/%'] = array(
        'title'            => t('Add New Hadis'),
        'description'      => t("Add new hadis with an efficient user interface."),
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('hadis_input_form', 2),
        'access arguments' => array('access administration pages'),
    );

    return $items;
}

function hadis_input_form($form, &$form_state, $selectedHadithBookId)
{
    $hadithBookCollection = hadis_input_get_hadith_book_collection();
    $primaryBanglaBook    = hadis_input_get_primary_bangla_book($selectedHadithBookId);
    $secondaryBanglaBook  = hadis_input_get_secondary_bangla_book($selectedHadithBookId);

    $selectedChapter = isset($form_state['values']['chapter']) ? $form_state['values']['chapter'] : isset($_SESSION['chapter']) ? $_SESSION['chapter'] : '';

    drupal_set_title($hadithBookCollection[$selectedHadithBookId]);

    $form['hadith_book_container'] = array(
        '#markup' => '<div class="container">'
    );

    $form['field_hadith_book'] = array(
        '#title'         => t('Hadith Book'),
        '#type'          => 'select',
        '#required'      => true,
        '#disabled'      => true,
        '#options'       => $hadithBookCollection,
        '#default_value' => $selectedHadithBookId,
        '#attributes'    => array("style" => "width: 150px"),
        '#prefix'        => '<div class="three columns first">',
        '#suffix'        => '</div>'
    );

    $form['field_hadith_book_chapter'] = array(
        '#title'         => t('Chapter'),
        '#type'          => 'select',
        '#required'      => true,
        '#options'       => hadis_input_get_chapter_collection($selectedHadithBookId),
        '#default_value' => $selectedChapter,
        '#attributes'    => array("style" => "width: 270px"),
        '#prefix'        => '<div id="chapter-container" class="five columns">',
        '#suffix'        => '</div>'
    );

    $form['field_section_arabic'] = array(
        '#title'    => t('Section (Arabic)'),
        '#type'     => 'textfield',
        '#size'     => 200,
        '#maxlength'=> 2000,
        '#required' => true,
        '#prefix'   => '<div class="twelve columns">',
        '#suffix'   => '</div>'
    );

    $form['field_section_english'] = array(
        '#title'    => t('Section (English)'),
        '#type'     => 'textfield',
        '#size'     => 200,
        '#maxlength'=> 2000,
        '#required' => true,
        '#prefix'   => '<div class="twelve columns">',
        '#suffix'   => '</div>'
    );

    $form['field_section_bangla_primary'] = array(
        '#title'    => t('Section (Bangla - ' . $primaryBanglaBook . ')'),
        '#type'     => 'textfield',
        '#size'     => 200,
        '#maxlength'=> 2000,
        '#required' => true,
        '#prefix'   => '<div class="twelve columns">',
        '#suffix'   => '</div>'
    );

    if ($secondaryBanglaBook) {

        $form['field_section_bangla_secondary'] = array(
            '#title'    => t('Section (Bangla - ' . $secondaryBanglaBook . ')'),
            '#type'     => 'textfield',
            '#size'     => 80,
            '#required' => true,
            '#prefix'   => '<div class="twelve columns">',
            '#suffix'   => '</div>'
        );

    }

    $form['field_additional_text_arabic'] = array(
        '#title'    => t('Additional Text (Arabic)'),
        '#type'     => 'textarea',
        '#size'     => 80,
        '#required' => false,
        '#prefix'   => '<div class="twelve columns">',
        '#suffix'   => '</div>'
    );

    $form['field_additional_text_bangla_pri'] = array(
        '#title'    => t('Additional Text (Bangla - ' . $primaryBanglaBook . ')'),
        '#type'     => 'textarea',
        '#size'     => 80,
        '#required' => false,
        '#prefix'   => '<div class="twelve columns">',
        '#suffix'   => '</div>'
    );

    if ($secondaryBanglaBook) {

        $form['field_additional_text_bangla_sec'] = array(
            '#title'    => t('Additional Text (Bangla - ' . $secondaryBanglaBook . ')'),
            '#type'     => 'textarea',
            '#size'     => 80,
            '#required' => false,
            '#prefix'   => '<div class="twelve columns">',
            '#suffix'   => '</div>'
        );

    }

    $form['field_additional_text_english'] = array(
        '#title'    => t('Additional Text (English)'),
        '#type'     => 'textarea',
        '#size'     => 80,
        '#required' => false,
        '#prefix'   => '<div class="twelve columns show-hide"><a href="#show">Show/Hide Additional Text (English)</a>',
        '#suffix'   => '</div>'
    );

    $form['hadith_book_container_close'] = array(
        '#markup' => '</div>'
    );

    $form['hadith_fieldset'] = array(
        '#type'   => 'fieldset',
        '#prefix' => '<div id="hadith-fieldset-wrapper">',
        '#suffix' => '</div>',
    );

    if (empty($form_state['num_hadith'])) {
        $form_state['num_hadith'] = 1;
    }

    for ($i = 0; $i < $form_state['num_hadith']; $i++) {

        if ($i == 0 && !empty($_SESSION['bangla_pri_hadith_num'])) {
            $lastHadithNumberInt = '<div class="last-saved-hadith">Last Saved Hadith No: ' . $_SESSION['international_hadith_num'] . '</div>';
            $lastHadithNumberBan = '<div class="last-saved-hadith">Last Saved Hadith No: ' . $_SESSION['bangla_pri_hadith_num'] . '</div>';
        } else {
            $lastHadithNumberInt = '';
            $lastHadithNumberBan = '';
        }

        $form['hadith_fieldset']['container-' . $i] = array(
            '#markup' => '<div class="container hadith-container"><div class="row hadith-data"><div class="nine columns"><h4>Hadith #' . ($i + 1)  . '</h4></div>'
        );

        $form['hadith_fieldset']['field_validity_' . $i] = array(
            '#type'     => 'select',
            '#options'  => array('সহিহ হাদিস', 'হাসান হাদিস', 'যয়ীফ হাদিস', 'জাল হাদিস'),
            '#default_value' => 0,
            '#required' => true,
            '#prefix'   => '<div class="three columns">',
            '#suffix'   => '</div>'
        );

        $form['hadith_fieldset']['field_scholar_reviewed_' . $i] = array(
            '#type'     => 'select',
            '#options'  => array('স্কলার রিভিউ হয়নি', 'স্কলার রিভিউ হয়েছে'),
            '#default_value' => 0,
            '#required' => true,
            '#prefix'   => '<div class="three columns">',
            '#suffix'   => '</div></div>'
        );

        $form['hadith_fieldset']['field_international_hadith_num_' . $i] = array(
            '#type'     => 'textfield',
            '#title'    => t('International Hadith #'),
            '#size'     => 25,
            '#required' => true,
            '#prefix'   => '<div class="four columns">',
            '#suffix'   => $lastHadithNumberInt . '</div>'
        );

        $form['hadith_fieldset']['field_english_hadith_body_' . $i] = array(
            '#type'     => 'textarea',
            '#title'    => t('English Hadith Text'),
            '#required' => true,
            '#prefix'   => '<div class="twelve columns">',
            '#suffix'   => '</div>'
        );

        $form['hadith_fieldset']['field_english_hadith_reference_' . $i] = array(
            '#type'     => 'textarea',
            '#title'    => t('English Hadith Reference'),
            '#required' => false,
            '#prefix'   => '<div class="offset-by-four twelve columns show-hide"><a href="#show">Show/Hide Reference</a>',
            '#suffix'   => '</div>'
        );

        $form['hadith_fieldset']['field_arabic_hadith_body_' . $i] = array(
            '#type'     => 'textarea',
            '#title'    => t('Arabic Hadith Text'),
            '#required' => true,
            '#prefix'   => '<div class="offset-by-four twelve columns">',
            '#suffix'   => '</div>'
        );

        $form['hadith_fieldset']['field_arabic_hadith_reference_' . $i] = array(
            '#type'     => 'textarea',
            '#title'    => t('Arabic Hadith Reference'),
            '#required' => false,
            '#prefix'   => '<div class="offset-by-four twelve columns show-hide"><a href="#show">Show/Hide Reference</a>',
            '#suffix'   => '</div>'
        );

        $form['hadith_fieldset']['field_bangla_pri_hadith_num_' . $i] = array(
            '#type'     => 'textfield',
            '#title'    => t($primaryBanglaBook . ' Hadith #'),
            '#size'     => 25,
            '#required' => true,
            '#prefix'   => '<div class="four columns">',
            '#suffix'   => $lastHadithNumberBan . '</div>'
        );

        $form['hadith_fieldset']['field_bangla_pri_hadith_body_' . $i] = array(
            '#type'     => 'textarea',
            '#title'    => t($primaryBanglaBook . ' Hadith Text'),
            '#required' => true,
            '#prefix'   => '<div class="twelve columns">',
            '#suffix'   => '</div>'
        );

        $form['hadith_fieldset']['field_bangla_pri_hadith_note_' . $i] = array(
            '#type'     => 'textarea',
            '#title'    => t($primaryBanglaBook . ' Hadith Footnote/Reference'),
            '#required' => false,
            '#prefix'   => '<div class="offset-by-four twelve columns show-hide"><a href="#show">Show/Hide Footnote/Reference</a>',
            '#suffix'   => '</div>'
        );

        if ($secondaryBanglaBook) {

            $form['hadith_fieldset']['field_bangla_sec_hadith_num_' . $i] = array(
                '#type'     => 'textfield',
                '#title'    => t($secondaryBanglaBook . ' Hadith #'),
                '#size'     => 25,
                '#required' => true,
                '#prefix'   => '<div class="four columns">',
                '#suffix'   => '</div>'
            );

            $form['hadith_fieldset']['field_bangla_sec_hadith_body_' . $i] = array(
                '#type'     => 'textarea',
                '#title'    => t($secondaryBanglaBook . ' Hadith Text'),
                '#required' => true,
                '#prefix'   => '<div class="twelve columns">',
                '#suffix'   => '</div>'
            );

            $form['hadith_fieldset']['field_bangla_sec_hadith_note_' . $i] = array(
                '#type'     => 'textarea',
                '#title'    => t($secondaryBanglaBook . ' Hadith Footnote/Reference'),
                '#required' => false,
                '#prefix'   => '<div class="offset-by-four twelve columns show-hide"><a href="#show">Show/Hide Footnote/Reference</a>',
                '#suffix'   => '</div>'
            );

        }

        $form['hadith_fieldset']['field_tags_' . $i] = array(
            '#type'     => 'textfield',
            '#title'    => t('Tags'),
            '#required' => false,
            '#size'     => 120,
            '#prefix'   => '<div class="offset-by-four twelve columns">',
            '#suffix'   => '</div>',
            '#attributes' => array('class' => array('tag-input'))
        );

        $form['hadith_fieldset']['container-end-' . $i] = array(
            '#markup' => '</div>'
        );

    }

    $form['hadith_fieldset']['add_more'] = array(
        '#type'   => 'submit',
        '#value'  => t('Add one more'),
        '#submit' => array('hadis_input_add_more_add_one'),
        '#ajax'   => array(
            'callback' => 'hadis_input_hadith_add_more_callback',
            'wrapper'  => 'hadith-fieldset-wrapper',
        ),
    );

    if ($form_state['num_hadith'] > 1) {
        $form['hadith_fieldset']['remove_name'] = array(
            '#type'   => 'submit',
            '#value'  => t('Remove last one'),
            '#submit' => array('hadis_input_add_more_remove_one'),
            '#ajax'   => array(
                'callback' => 'hadis_input_hadith_add_more_callback',
                'wrapper'  => 'hadith-fieldset-wrapper',
            ),
        );
    }

    $form['submit'] = array(
        '#type'   => 'submit',
        '#value'  => 'Save Hadith',
        '#prefix' => '<div class="four columns" style="margin-left: 0">',
        '#suffix' => '</div>'
    );

    $path = drupal_get_path('module', 'hadis_input');
    drupal_add_css($path . '/hadith_input.css');

    return $form;
}

function hadis_input_form_submit($form, &$form_state)
{
    hadis_input_create_hadith($form_state['values']);
    drupal_set_message("Hadith created successfully.");
}

function hadis_input_hadith_add_more_callback($form, &$form_state)
{
    return $form['hadith_fieldset'];
}

function hadis_input_add_more_add_one($form, &$form_state)
{
    $form_state['num_hadith']++;
    $form_state['rebuild'] = true;
}

function hadis_input_add_more_remove_one($form, &$form_state)
{
    if ($form_state['num_hadith'] > 1) {
        $form_state['num_hadith']--;
    }

    $form_state['rebuild'] = true;
}

function hadis_input_create_hadith($data)
{
    $garbage = array('add_more', 'remove_name', 'submit', 'form_build_id', 'form_token', 'form_id', 'op');

    $commons = array('field_hadith_book', 'field_hadith_book_chapter', 'field_section_arabic', 'field_section_english',
                     'field_section_bangla_primary', 'field_section_bangla_secondary', 'field_additional_text_arabic',
                     'field_additional_text_english', 'field_additional_text_bangla_pri', 'field_additional_text_bangla_sec');

    $hadiths = array();

    foreach ($garbage as $key) {
        unset($data[$key]);
    }

    foreach ($data as $key => $value) {
        if (!in_array($key, $commons)) {
            $index = substr($key, strrpos($key, '_') + 1);
            $field = substr($key, 0, strrpos($key, '_'));
            $hadiths[$index][$field] = $value;
        }
    }

    foreach ($hadiths as $hadith) {
        hadis_input_insert_node($hadith, $data);
        hadis_input_save_session($hadith, $data);
    }
}

function hadis_input_insert_node($data, $additional)
{
    global $user;

    $node = new stdClass();
    $node->type = "hadith";

    node_object_prepare($node);

    $node->language = LANGUAGE_NONE;
    $node->uid = $user->uid;
    $node->comment = 2;
    $node->promote = 1;

    $termBook = taxonomy_term_load($additional['field_hadith_book']);
    $termChapter = taxonomy_term_load($additional['field_hadith_book_chapter']);

    // Primary information
    $node->title = hadis_input_get_title($data, $termBook, $termChapter);
    $node->body[$node->language][0]['value']   = $data['field_bangla_pri_hadith_body'];
    $node->body[$node->language][0]['summary'] = text_summary($data['field_bangla_pri_hadith_body']);
    $node->body[$node->language][0]['format']  = 'filtered_html';

    $node->field_hadith_book[$node->language][]['tid'] = $additional['field_hadith_book'];
    $node->field_hadith_book_chapter[$node->language][]['tid'] = $additional['field_hadith_book_chapter'];

    // Sections
    $node->field_section_arabic[$node->language][0]['value']             = $additional['field_section_arabic'];
    $node->field_section_english[$node->language][0]['value']            = $additional['field_section_english'];
    $node->field_section_bangla_primary[$node->language][0]['value']     = $additional['field_section_bangla_primary'];

    // Additional text
    if (isset($additional['field_section_bangla_secondary'])) {
        $node->field_section_bangla_secondary[$node->language][0]['value'] = $additional['field_section_bangla_secondary'];
    }

    if (isset($additional['field_additional_text_arabic'])) {
        $node->field_additional_text_arabic[$node->language][0]['value'] = $additional['field_additional_text_arabic'];
    }

    if (isset($additional['field_additional_text_english'])) {
        $node->field_additional_text_english[$node->language][0]['value'] = $additional['field_additional_text_english'];
    }

    if (isset($additional['field_additional_text_bangla_pri'])) {
        $node->field_additional_text_bangla_pri[$node->language][0]['value'] = $additional['field_additional_text_bangla_pri'];
    }

    if (isset($additional['field_additional_text_bangla_sec'])) {
        $node->field_additional_text_bangla_sec[$node->language][0]['value'] = $additional['field_additional_text_bangla_sec'];
    }

    // Validity and review
    $node->field_validity[$node->language][0]['value']                 = $data['field_validity'];
    $node->field_scholar_reviewed[$node->language][0]['value']         = $data['field_scholar_reviewed'];

    // Primary bangla
    $node->field_bangla_pri_hadith_num[$node->language][0]['value']    = $data['field_bangla_pri_hadith_num'];
    $node->field_bangla_pri_hadith_body[$node->language][0]['value']   = $data['field_bangla_pri_hadith_body'];

    if (isset($data['field_bangla_pri_hadith_note'])) {
        $node->field_bangla_pri_hadith_note[$node->language][0]['value'] = $data['field_bangla_pri_hadith_note'];
    }

    // Secondary bangla
    if (isset($data['field_bangla_sec_hadith_num'])) {
        $node->field_bangla_sec_hadith_num[$node->language][0]['value'] = $data['field_bangla_sec_hadith_num'];
    }

    if (isset($data['field_bangla_sec_hadith_body'])) {
        $node->field_bangla_sec_hadith_body[$node->language][0]['value'] = $data['field_bangla_sec_hadith_body'];
    }

    if (isset($data['field_bangla_sec_hadith_note'])) {
        $node->field_bangla_sec_hadith_note[$node->language][0]['value'] = $data['field_bangla_sec_hadith_note'];
    }

    // International
    $node->field_international_hadith_num[$node->language][0]['value'] = $data['field_international_hadith_num'];
    $node->field_arabic_hadith_body[$node->language][0]['value'] = $data['field_arabic_hadith_body'];

    if (isset($data['field_arabic_hadith_reference'])) {
        $node->field_arabic_hadith_reference[$node->language][0]['value']  = $data['field_arabic_hadith_reference'];
    }

    // English
    $node->field_english_hadith_body[$node->language][0]['value'] = $data['field_english_hadith_body'];

    if (isset($data['field_english_hadith_reference'])) {
        $node->field_english_hadith_reference[$node->language][0]['value'] = $data['field_english_hadith_reference'];
    }

    // Tags
    $tags = explode(",", $data['field_tags']);

    if (count($tags) > 0) {

        foreach ($tags as $tag) {

            $tag = trim($tag);
            $term = taxonomy_get_term_by_name($tag);

            if (empty($term)) {
                $tid = hadis_input_create_term($tag);
            } else {
                $keys = array_keys($term);
                $tid = $keys[0];
            }

            $node->field_tags[$node->language][]['tid'] = $tid;

        }

    }

    if ($node = node_submit($node)) { // Prepare node for saving
        node_save($node);
    }
}

function hadis_input_save_session($data, $additional)
{
    $_SESSION['chapter'] = $additional['field_hadith_book_chapter'];
    $_SESSION['bangla_pri_hadith_num'] = $data['field_bangla_pri_hadith_num'];
    $_SESSION['international_hadith_num'] = $data['field_international_hadith_num'];
}