parameters:

services:

    # Event Listeners
    doctrine.listener:
        class: Ihadis\Bundle\CoreBundle\EventListener\DoctrineListener
        arguments: [@service_container]
        tags:
          - { name: doctrine.event_listener, event: prePersist, method: prePersist }
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }
          - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
          - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }

    tag.change.listener:
        class: Ihadis\Bundle\CoreBundle\EventListener\TagChangeListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: ihadis.hadith.pre_create, method: onHadisPreCreate }
          - { name: kernel.event_listener, event: ihadis.hadith.pre_update, method: onHadisPreUpdate }
