<?php

namespace Ihadis\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HadithRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HadithRepository extends EntityRepository
{
    /**
     * Get Hadiths by Section
     */
    public function getBySectionId($sectionId)
    {
        $result = $this->createQueryBuilder('h')
                    ->where('h.section = :section')
                    ->setParameter('section', $sectionId)
                    ->orderBy('h.numberPrimary', 'asc')
                    ->getQuery()
                    ->getResult();

        return $result;
    }

    /**
     * Get Hadiths by Section
     */
    public function search($keyword, $page)
    {
        $result = $this->createQueryBuilder('h')
            ->join('h.translations', 't')
            ->where('h.body LIKE :keyword')
            ->orWhere('t.body LIKE :keyword')
            ->setParameter('keyword', "%$keyword%")
            ->orderBy('h.numberPrimary', 'asc')
            ->setFirstResult($page)
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();

        return $result;
    }
}