<?php

namespace Ihadis\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HadithRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HadithRepository extends EntityRepository
{
}
