<?php

namespace Ihadis\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HadithRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HadithRepository extends EntityRepository
{
    /**
     * Get Hadiths by Section
     */
    public function getBySectionId($sectionId)
    {
        $result = $this->createQueryBuilder('h')
                    ->where('h.section = :section')
                    ->setParameter('section', $sectionId)
                    ->orderBy('h.numberPrimary', 'asc')
                    ->getQuery()
                    ->getResult();

        return $result;
    }
}