ihadis_chapter_list:
    pattern: /{book}
    methods: [GET]
    defaults:
        _controller: ihadis.controller.chapter:indexAction
        _sylius:
            criteria:
                book: $book

ihadis_chapter_add:
    pattern: /add/{book}
    methods: [GET, POST]
    defaults:
        _controller: ihadis.controller.chapter:createAction
        _sylius:
            redirect:
                route: ihadis_chapter_list
                parameters:
                    book: $book
            _sylius:
                criteria:
                    book: $book

ihadis_chapter_edit:
    pattern: /{id}/book/{book}/edit
    methods: [GET, PUT]
    defaults:
        _controller: ihadis.controller.chapter:updateAction
        _sylius:
            redirect:
                route: ihadis_chapter_list
                parameters:
                    book: $book
            _sylius:
                criteria:
                    book: $book

ihadis_chapter_delete:
    pattern: /{id}/book/{book}
    methods: [DELETE]
    defaults:
        _controller: ihadis.controller.chapter:deleteAction
        _sylius:
            redirect:
                route: ihadis_chapter_list
                parameters:
                    book: $book
            _sylius:
                criteria:
                    book: $book