ihadis_book:
    resource: "@IhadisCoreBundle/Resources/config/routes/book.yml"
    prefix:   /books

ihadis_book:
    resource: "@IhadisCoreBundle/Resources/config/routes/chapter.yml"
    prefix:   /chapters

ihadis_section:
    resource: "@IhadisCoreBundle/Resources/config/routes/section.yml"
    prefix:   /sections

ihadis_core_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IhadisCoreBundle:Default:index }
