ihadis_book:
    resource: "@IhadisCoreBundle/Resources/config/routes/book.yml"
    prefix:   /admin/books

ihadis_book:
    resource: "@IhadisCoreBundle/Resources/config/routes/chapter.yml"
    prefix:   /admin/chapters

ihadis_section:
    resource: "@IhadisCoreBundle/Resources/config/routes/section.yml"
    prefix:   /admin/sections

ihadis_hadith:
    resource: "@IhadisCoreBundle/Resources/config/routes/hadith.yml"
    prefix:   /admin/hadiths

ihadis_core_homepage:
    pattern:  /
    defaults: { _controller: IhadisCoreBundle:Default:index }
