parameters:
#    ihadis_core.example.class: Ihadis\Bundle\CoreBundle\Example

services:
#    ihadis_core.example:
#        class: %ihadis_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
